J-Tech-Japan/Sekiban

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/Program.cs, docs/docfx_project/articles/sekiban-event-sourcing-basics.md, docs/docfx_project/articles/test-out-cosmos.md, docs/docfx_project/articles_ja/sekiban-event-sourcing-basics.md, docs/docfx_project/articles_ja/test-out-cosmos.md, samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowingWebDependency.cs
- Update of dependent libraries (including Sekiban)
- Fix build errors in the sample for DynamoDB
- Related Issue #174 
=> Update sample project.

src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
package build failed and its fix
=> fix readme path

src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
change readme relative path
hopefully it fixes build error on nuget build.
=> change readme relative path

Samples/Tutorials/1.GetStarted/.idea/.idea.GetStarted/.idea/vcs.xml, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/appsettings.Development.json, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj
Updated Sample project nugets to new version
none
=> Update Samples to new sekiban nuget version

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/appsettings.Development.json, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/appsettings.Development.json, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Cosmos/SekibanCosmosDbOptions.cs, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Dynamo/SekibanDynamoDbOptions.cs, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
=> fix from 0.16.0

Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/appsettings.Development.json
removed section.
- Related Issue #194 
- Closes #
=> Update appsettings.Development.json removed unnecessary section.

src/Sekiban.Infrastructure.Cosmos/CosmosDbFactory.cs, src/Sekiban.Infrastructure.Cosmos/CosmosDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDbDocumentRemover.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentWriter.cs, tools/ConvertAndCopyCosmosItems/EventsConverter.cs
CosmosDbFactory can be swapped with another implementation ( for aspire )
- Related Issue #197 
- Closes #
=> Add ICosmosDbFactory

src/Sekiban.Infrastructure.Cosmos/SekibanAzureOption.cs
- Related Issue #196 
- Closes #196 
I wrote a sample program and confirmed that it works without any problems.
=> Give default values to the public properties of the SekibanAzureOption class

Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, internalUsages/FeatureCheck.WebApi.Dynamo/Program.cs, internalUsages/FeatureCheck.WebApi/Program.cs, internalUsages/MultiTenant.WebApi/Program.cs, src/Sekiban.Core/Dependency/SekibanEventSourcingDependency.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/CosmosDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/DynamoDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
Adding WebApplicationBuilder extension to simplify app initialization.
- Related Issue #200
=> Adding WebApplicationBuilder extension

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/Program.cs, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/Program.cs, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, docs/docfx_project/articles/sekiban-event-sourcing-basics.md, docs/docfx_project/articles_ja/sekiban-event-sourcing-basics.md
Update document and sample to 0.16.2
- Related Issue #203
- Closes #203
=> Update samples to Sekiban 0.16.2

src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Cosmos/SekibanCosmosDbOptions.cs, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
when default appsettings section is empty, it will use default object.
Instead for empty.
- Related Issue #209
- Closes #209
=> 209 sekiban  default  azure  cosmosdatabase is not woking with default value

src/Sekiban.Web/OpenApi/Extensions/SwaggerGenExtensions.cs, src/Sekiban.Web/Sekiban.Web.csproj
Upgrade Jtechs.OpenApi.AspNetCore.Swashbuckle package to version 0.2.1
- Related Issue #227 
- Closes #227
=> Upgrade Jtechs.OpenApi.AspNetCore.Swashbuckle package to version 0.2.1

internalUsages/FeatureCheck.Domain/Aggregates/Branches/Queries/BranchExistsQuery.cs, internalUsages/FeatureCheck.Domain/Aggregates/Clients/Queries/GetClientPayloadQuery.cs, internalUsages/FeatureCheck.Domain/Shared/FeatureCheckDependency.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Documents/ValueObjects/SortableUniqueIdValue.cs, src/Sekiban.Core/Query/MultiProjections/IMultiProjectionService.cs, src/Sekiban.Core/Query/MultiProjections/MultiProjectionService.cs, src/Sekiban.Core/Query/MultiProjections/Projections/IMultiProjection.cs, src/Sekiban.Core/Query/MultiProjections/Projections/MemoryCacheMultiProjection.cs, src/Sekiban.Core/Query/MultiProjections/Projections/MultiProjectionRetrievalOptions.cs, src/Sekiban.Core/Query/MultiProjections/Projections/SimpleMultiProjection.cs, src/Sekiban.Core/Query/QueryModel/IQueryParameterCommon.cs, src/Sekiban.Core/Query/QueryModel/QueryExecutor.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Testing/UnifiedTest.cs, src/Sekiban.Web/Sekiban.Web.csproj, tests/Sekiban.Test.CosmosDb/Stories/Abstracts/CustomerDbStoryBasic.cs
Query can now add MultiProjectionRetrievalOptions 
- Related Issue #232
- Closes #232
=> 232 query needs without new retrieval option

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj
- Related Issue #234
- Closes #234
=> Adopt aspire preview 3

internalUsages/FeatureCheck.Domain/Aggregates/Clients/Commands/ChangeClientNameWithoutLoading.cs, internalUsages/FeatureCheck.Domain/Shared/FeatureCheckDependency.cs, src/Sekiban.Core/Query/SingleProjections/AggregateLoader.cs, src/Sekiban.Core/Query/SingleProjections/IAggregateLoader.cs, src/Sekiban.Core/Query/SingleProjections/Projections/ISingleProjection.cs, src/Sekiban.Core/Query/SingleProjections/Projections/MemoryCacheSingleProjection.cs, src/Sekiban.Core/Query/SingleProjections/Projections/SimpleProjectionWithSnapshot.cs, src/Sekiban.Web/Controllers/Bases/BaseGetAggregateController.cs, src/Sekiban.Web/Controllers/Bases/BaseSingleProjectionController.cs, tests/Sekiban.Test.CosmosDb/Stories/Abstracts/CustomerDbStoryBasic.cs
- Related Issue #236 
- Closes #236
=> Add Single Projection Retrieval Options

.github/workflows/packages.yml, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
- Related Issue #247
- Closes #247
=> add blob package

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Command/CommandExecutor.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
Add original command information on the histories
- Related Issue #252
- Closes #252
=> 252 command converter needs to keep add histories

src/Sekiban.Testing/Command/TestCommandExecutor.cs, tests/FeatureCheck.Test/AggregateTests/DerivedTypeSpec.cs
- Related Issue #253
- Closes #253
=> Execute Command work with the environment as well

src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj
fix package mistake
- Related Issue #256
- Closes #256
=> fix package mistake

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/Program.cs, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/Program.cs, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/appsettings.Development.json, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj
updated samples to new sekiban versions
- Related Issue #258 
- Closes #258 
=> updated samples to new sekiban versions

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, internalUsages/FeatureCheck.WebApi.Postgres/Program.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/PostgresDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Infrastructure.Postgres/SekibanPostgresDbOption.cs, src/Sekiban.Infrastructure.Postgres/SekibanPostgresOptions.cs, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
Sekiban Postgres setting from ConnectionStringName
- Related Issue #261
- Closes #261
=> Sekiban Postgres setting from ConnectionStringName

.idea/.idea.Sekiban/.idea/.gitignore, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
update to the aspire 8.0 preview 4
- Related Issue #266
- Closes #266
=> update to the aspire 8.0 preview 4

Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Web/Program.cs
- Related Issue #266
- Closes #266
=> indent settings

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/Program.cs, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/Program.cs, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj, docs/docfx_project/articles/sekiban-event-sourcing-basics.md, docs/docfx_project/articles_ja/sekiban-event-sourcing-basics.md
- Related Issue #274 
- Closes #274 
=> update smaple and document

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/SekibanBlobAspireExtensions.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/SekibanCosmosAspireExtensions.cs
change aspire version to the newest preview
- Related Issue #278
- Closes #278
=> change aspire version to preview 5

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/appsettings.Development.json, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Properties/launchSettings.json, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/Extensions.cs
283 update samples to aspire preview 5
- Closes #
=> 283 update samples to aspire preview 5

Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/Program.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/Aggregates/AccountUsers/AccountUser.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSampleDomainDependency.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Web/WeatherApiClient.cs
update samples for aspire preview 5
- Related Issue #283 
- Closes #283 
=> update samples for aspire preview 5

Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj, internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.Abstructs/Sekiban.Test.Abstructs.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj, tests/Sekiban.Test.Postgres/Sekiban.Test.Postgres.csproj, tools/ConvertAndCopyCosmosItems/ConvertAndCopyCosmosItems.csproj
aspire and nuget version update
- Related Issue #287
=> aspire and nuget version update

Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj
update to aspire preview 6 for samples
- Related Issue #287
- Closes #287
=> update to aspire preview 6 sample

.github/workflows/packages.yml, .github/workflows/run_test.yml, internalUsages/FeatureCheck.Domain/FeatureCheck.Domain.csproj, internalUsages/FeatureCheck.WebApi/FeatureCheck.WebApi.csproj, internalUsages/Mixed.Domain/Mixed.Domain.csproj, internalUsages/MultiTenant.Domain/MultiTenant.Domain.csproj, internalUsages/MultiTenant.WebApi/MultiTenant.WebApi.csproj, internalUsages/SampleProject.Common/SampleProject.Common.csproj, internalUsages/Shipping.Domain/Shipping.Domain.csproj, internalUsages/Shipping.Port/Shipping.Port.csproj, internalUsages/Warehouse.Domain/Warehouse.Domain.csproj, internalUsages/Warehouse.Port/Warehouse.Port.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.Abstructs/Sekiban.Test.Abstructs.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj, tests/Sekiban.Test.Postgres/Sekiban.Test.Postgres.csproj, tools/ConvertAndCopyCosmosItems/ConvertAndCopyCosmosItems.csproj
removed dotnet 7
- Related Issue #290
- Closes #290
=> 290 remove dotnet 7

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample.Domain.Test/Postgres.Sample.Domain.Test.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample.Domain/Postgres.Sample.Domain.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample/Postgres.Sample.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj
Update samples to sekiban version to 0.19.1
- Related Issue #293 
- Closes #293 
=> Update sekiban version to 0.19.1

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Command/ITenantCommandCommon.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
ITenantCommandCommon does not need init;
- Related Issue #300
- Closes #300
=> Itenantcommandcommon does not need init

src/Sekiban.Core/Command/CommandExecutor.cs, src/Sekiban.Core/Command/ICommandExecutor.cs, src/Sekiban.Core/Command/StaticCommandHandlerAdapter.cs, src/Sekiban.Core/Command/StaticCommandWithoutLoadingAggregateHandlerAdapter.cs, src/Sekiban.Testing/Command/TestCommandExecutor.cs, src/Sekiban.Testing/SingleProjections/AggregateTestHelper.cs
Changed to result first
- Related Issue #304
- Closes #304
=> Changed to result first

internalUsages/FeatureCheck.Domain/Aggregates/Clients/Commands/CreateClientWithResult.cs, src/Sekiban.Core/Types/QueryHandlerTypesExtension.cs
fix query url mistake
- Related Issue #318 
- Closes #318
=> fix query url mistake

internalUsages/FeatureCheck.Domain/Aggregates/Clients/Commands/CreateClientWithResult.cs, internalUsages/FeatureCheck.Domain/Aggregates/TenantUsers/CreateTenantUser.cs, internalUsages/FeatureCheck.Domain/Projections/GeneralListQuerySampleNext.cs, internalUsages/FeatureCheck.Domain/Projections/GeneralQuerySampleNext.cs, internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, src/Sekiban.Core/Command/CommandHandlerAdapter.cs, src/Sekiban.Core/Command/ICommandContextWithoutGetState.cs, src/Sekiban.Core/Command/StaticCommandHandlerAdapter.cs, src/Sekiban.Core/Command/StaticCommandWithoutLoadingAggregateHandlerAdapter.cs, src/Sekiban.Core/Dependency/SekibanEventSourcingDependency.cs, src/Sekiban.Core/Query/QueryModel/IQueryContext.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.Abstructs/Sekiban.Test.Abstructs.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj, tests/Sekiban.Test.Postgres/Sekiban.Test.Postgres.csproj
Add context methods
- Related Issue #316 
- Closes #316 
=> Add context methods

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Command/CommandHandlerAdapter.cs, src/Sekiban.Core/Command/ICommandContextWithoutGetState.cs, src/Sekiban.Core/Command/StaticCommandHandlerAdapter.cs, src/Sekiban.Core/Command/StaticCommandWithoutLoadingAggregateHandlerAdapter.cs, src/Sekiban.Core/Dependency/SekibanCoreServiceExtensions.cs, src/Sekiban.Core/ISekibanExecutor.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/Sekiban.Test.Abstructs/Abstructs/ResultBoxSpec.cs, tests/Sekiban.Test.Abstructs/Abstructs/TestBase.cs
Adding SekibanExecutor
- Related Issue #317 
- Closes #317
=> Adding SekibanExecutor

src/Sekiban.Web/Common/SekibanControllerRouteConvention.cs
fix query url
- Related Issue #325
- Closes #325
=> fix query url

internalUsages/FeatureCheck.Domain/Aggregates/ALotOfEvents/Commands/ALotOfEventsCreateCommandNext.cs, internalUsages/FeatureCheck.Domain/Aggregates/ALotOfEvents/Commands/TwoEventsCreateCommand.cs, internalUsages/FeatureCheck.Domain/Aggregates/Branches/Commands/ChangeBranchNameNext.cs, internalUsages/FeatureCheck.Domain/Aggregates/Branches/Commands/CreateBranchWithResult.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Command/CommandHandlerAdapter.cs, src/Sekiban.Core/Command/ICommandContextWithoutGetState.cs, src/Sekiban.Core/Command/StaticCommandHandlerAdapter.cs, src/Sekiban.Core/Command/StaticCommandWithoutLoadingAggregateHandlerAdapter.cs, src/Sekiban.Core/ISekibanExecutor.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Core/SekibanExecutor.cs, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/AggregateTests/AlotOfEventsSpec.cs
324 needs contextappendevents multiple add
- Related Issue #324
- Closes #324
=> 324 needs contextappendevents multiple add

internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentRepository.cs, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.Abstructs/Sekiban.Test.Abstructs.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj, tests/Sekiban.Test.Postgres/Sekiban.Test.Postgres.csproj
Updated Packages
- Related Issue #332
- Closes #332
=> Updated Packages

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Cosmos.Web/SekibanEventSourcingBasics.Cosmos.Web.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Domain/SekibanEventSourcingBasics.Domain.csproj, Samples/Tutorials/2.SekibanEventSourcingBasics/SekibanEventSourcingBasics.Testing/SekibanEventSourcingBasics.Testing.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample.Domain.Test/Postgres.Sample.Domain.Test.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample.Domain/Postgres.Sample.Domain.csproj, Samples/Tutorials/3.PostgresSample/Postgres.Sample/Postgres.Sample/Postgres.Sample.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService.Postgres/AspireAndSekibanSample.ApiService.Postgres.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ApiService/AspireAndSekibanSample.ApiService.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.AppHost/AspireAndSekibanSample.AppHost.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/Aggregates/AccountUsers/AccountUser.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSample.Domain.csproj, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.Domain/AspireAndSekibanSampleDomainDependency.cs, Samples/Tutorials/AspireAndSekibanSample/AspireAndSekibanSample.ServiceDefaults/AspireAndSekibanSample.ServiceDefaults.csproj
Update sample program to newest sekiban.
- Related Issue #334
- Closes #334
=> Update sample program to newest sekiban.

internalUsages/FeatureCheck.Domain/Aggregates/Clients/Queries/ClientEmailExistQueryNext.cs, internalUsages/FeatureCheck.Domain/Aggregates/Clients/Queries/GetClientPayloadQueryNext.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Query/QueryModel/INextListQueryCommon.cs, src/Sekiban.Core/Query/QueryModel/INextQueryCommon.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Testing/SingleProjections/AggregateTest.cs, src/Sekiban.Testing/SingleProjections/AggregateTestHelper.cs, src/Sekiban.Testing/SingleProjections/IAggregateTestHelper.cs, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/AggregateTests/ResultClientSpec.cs
Add query test functions.
- Related Issue #336
- Closes #336
=> 336 test thenquerythrows needs inextlistquery implementation

src/Sekiban.Testing/SingleProjections/AggregateTest.cs, src/Sekiban.Testing/SingleProjections/AggregateTestHelper.cs, src/Sekiban.Testing/SingleProjections/IAggregateTestHelper.cs, src/Sekiban.Testing/UnifiedTest.cs
working on unifiedtest next query
- Related Issue #342
- Closes #342
=> working on unifiedtest next query

internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, internalUsages/FeatureCheck.WebApi/FeatureCheck.WebApi.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Query/QueryModel/ListQueryResult.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Core/Types/GeneralTypeExtensions.cs, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/Sekiban.Test.Abstructs/Abstructs/ResultBoxSpec.cs
Add ListQueryResult<T>.Empty
- Related Issue #349
- Closes #349
=> Add ListQueryResult<T>.Empty

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
updated resultbox
updated resultbox
- Related Issue #353
- Closes #353
=> updated resultbox

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
Add Version
- Related Issue #360
- Closes #360
=> Add Version

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Command/ICommandWithHandlerForExistingAggregateAsync.cs, src/Sekiban.Core/Command/ICommandWithHandlerWithVersionValidation.cs, src/Sekiban.Core/Command/ICommandWithHandlerWithVersionValidationAsync.cs, src/Sekiban.Core/Command/ICommandWithHandlerWithVersionValidationForExistingAggregate.cs, src/Sekiban.Core/Command/ICommandWithHandlerWithVersionValidationForExistingAggregateAsync.cs, src/Sekiban.Core/Command/ITenantCommandWithHandler.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerForExistingAggregate.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerForExistingAggregateAsync.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithVersionValidation.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithVersionValidationAsync.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithVersionValidationForExistingAggregate.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithVersionValidationForExistingAggregateAsync.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithoutLoadingAggregate.cs, src/Sekiban.Core/Command/ITenantCommandWithHandlerWithoutLoadingAggregateAsync.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
Updated Command to implement ICommandCommon<
- Related Issue #364
- Closes #364
=> Updated Command to implement ICommandCommon<

internalUsages/FeatureCheck.Domain/Aggregates/Branches/Queries/BranchExistsQueryN.cs, internalUsages/FeatureCheck.Domain/Aggregates/DeletebleBoxes/Box.cs, src/Sekiban.Core/Query/QueryModel/INextAggregateListQuery.cs, src/Sekiban.Core/Query/QueryModel/INextAggregateListQueryAsync.cs, src/Sekiban.Core/Query/QueryModel/INextAggregateQuery.cs, src/Sekiban.Core/Query/QueryModel/INextAggregateQueryAsync.cs, src/Sekiban.Core/Query/QueryModel/INextSingleProjectionListQuery.cs, src/Sekiban.Core/Query/QueryModel/INextSingleProjectionListQueryAsync.cs, src/Sekiban.Core/Query/QueryModel/INextSingleProjectionQuery.cs, src/Sekiban.Core/Query/QueryModel/INextSingleProjectionQueryAsync.cs, src/Sekiban.Core/Query/QueryModel/QueryExecutor.cs, src/Sekiban.Testing/Command/TestCommandExecutor.cs, src/Sekiban.Testing/UnifiedTest.cs, tests/FeatureCheck.Test/QueryTests/GeneralQuerySampleSpec.cs
QueryListType should be static GetQueryListType
- Related Issue #370
- Closes #370
=> QueryListType should be static GetQueryListType

internalUsages/FeatureCheck.Domain/Aggregates/AccessingCommands/AccessingCommand.cs, src/Sekiban.Core/Aggregate/Aggregate.cs, src/Sekiban.Core/Command/CommandHandlerAdapter.cs, src/Sekiban.Core/Command/ICommandContext.cs, src/Sekiban.Core/Command/ICommandDocumentCommon.cs, src/Sekiban.Core/Command/StaticCommandHandlerAdapter.cs, tests/FeatureCheck.Test/AggregateTests/AccessingCommandTests.cs
Add Command Informations
- Related Issue #359
- Closes #359
=> Add Command Informations

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
0.22.0-preview4
- Related Issue #376
- Closes #376
=> For new version 0.22.0-preview4

internalUsages/MemStat.Net.Web/Program.cs, src/MemStat.Net/IMemoryUsageFinder.cs, src/MemStat.Net/LinuxMemoryUsageFinder.cs, src/MemStat.Net/MacMemoryUsageFinder.cs, src/MemStat.Net/MemStat.Net.csproj, src/MemStat.Net/MemoryUsageFinder.cs, src/MemStat.Net/MemoryUsageFinderExtensions.cs, src/MemStat.Net/WindowsMemoryInfo.cs, src/MemStat.Net/WindowsMemoryUsageFinder.cs, src/Sekiban.Core/Dependency/SekibanCoreServiceExtensions.cs
Improve Memory Usage Finder to switch when set up services
- Related Issue #385
- Closes #385
=> Improve Memory Usage Finder to switch when set up services

.github/workflows/packages.yml, internalUsages/MemStat.Net.Web/Program.cs, src/MemStat.Net/MemStat.Net.csproj, src/MemStat.Net/README.md, src/Sekiban.Core/Documents/IPooledEventWriter.cs
Release MemStat
- Related Issue #387
- Closes #387
=> Release MemStat

.github/workflows/packageMemStat.yml, src/MemStat.Net/MemStat.Net.csproj, src/MemStat.Net/README.md, src/Sekiban.Core/Sekiban.Core.csproj
add more document on memstat.net
- Related Issue #387 
- Closes #387
=> add more document on memstat.net

src/Sekiban.Core/Dependency/SekibanCoreServiceExtensions.cs, src/Sekiban.Core/Documents/DocumentRepositorySplitter.cs, src/Sekiban.Core/Documents/IDocumentRepository.cs, src/Sekiban.Core/Documents/IPooledEventWriter.cs, src/Sekiban.Core/Documents/InMemoryDocumentRepository.cs, src/Sekiban.Core/Partition/PartitionKeyGenerator.cs, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosPartitionGenerator.cs, src/Sekiban.Infrastructure.Dynamo/Documents/DynamoDocumentRepository.cs, src/Sekiban.Infrastructure.Dynamo/Documents/QueryFilterExtensions.cs, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentRepository.cs
add general getevents function
- Related Issue #393
- Closes #393
=> 393 add general getevents function

src/README.md, src/Sekiban.Core/Command/CommandExecutor.cs, src/Sekiban.Core/Documents/DocumentRepositorySplitter.cs, src/Sekiban.Core/Documents/DocumentWriterSplitter.cs, src/Sekiban.Core/Documents/IDocumentPersistentWriter.cs, src/Sekiban.Core/Documents/IDocumentRepository.cs, src/Sekiban.Core/Documents/IDocumentWriter.cs, src/Sekiban.Core/Documents/InMemoryDocumentRepository.cs, src/Sekiban.Core/Documents/InMemoryDocumentWriter.cs, src/Sekiban.Core/Documents/Pools/IAggregatesStream.cs, src/Sekiban.Core/Documents/Pools/IPooledEventWriter.cs, src/Sekiban.Core/Query/MultiProjections/Projections/MultiProjectionSnapshotGenerator.cs, src/Sekiban.Core/Snapshot/BackgroundServices/SnapshotGenerator.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentWriter.cs, src/Sekiban.Infrastructure.Dynamo/Documents/DynamoDocumentRepository.cs, src/Sekiban.Infrastructure.Dynamo/Documents/DynamoDocumentWriter.cs, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentRepository.cs, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentWriter.cs, src/Sekiban.Testing/Command/TestCommandExecutor.cs, src/Sekiban.Testing/Projection/TestEventHandler.cs, src/Sekiban.Testing/SingleProjections/AggregateTestHelper.cs, tests/Sekiban.Test.Abstructs/Abstructs/AggregateSubtypeTest.cs, tests/Sekiban.Test.Abstructs/Abstructs/CustomerDbStoryBasic.cs, tests/Sekiban.Test.CosmosDb/Stories/InheritedSubtypeTests.cs
Working on the Writer Abstraction
=> Working on the Writer Abstraction

src/MemStat.Net/ProcessToStringList.cs, src/Sekiban.Core/Command/CommandExecutor.cs, src/Sekiban.Core/Dependency/SekibanCoreServiceExtensions.cs, src/Sekiban.Core/Documents/DocumentWriterSplitter.cs, src/Sekiban.Core/Documents/IDocumentPersistentWriter.cs, src/Sekiban.Core/Documents/IDocumentWriter.cs, src/Sekiban.Core/Documents/InMemoryDocumentWriter.cs, src/Sekiban.Core/Documents/Pools/IPooledEventWriter.cs, src/Sekiban.Core/PubSub/EventPublisher.cs, src/Sekiban.Core/Query/MultiProjections/Projections/MultiProjectionSnapshotGenerator.cs, src/Sekiban.Core/Snapshot/BackgroundServices/SnapshotGenerator.cs, src/Sekiban.Infrastructure.Cosmos/CosmosDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentWriter.cs, src/Sekiban.Infrastructure.Dynamo/Documents/DynamoDocumentWriter.cs, src/Sekiban.Infrastructure.Dynamo/DynamoDbServiceCollectionExtensions.cs, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentWriter.cs, src/Sekiban.Infrastructure.Postgres/PostgresDbServiceCollectionExtensions.cs, src/Sekiban.Testing/Command/TestCommandExecutor.cs, src/Sekiban.Testing/Projection/TestEventHandler.cs, src/Sekiban.Testing/SingleProjections/AggregateTest.cs, src/Sekiban.Testing/SingleProjections/AggregateTestHelper.cs, src/Sekiban.Testing/SingleProjections/IAggregateTestHelper.cs
Separated Event Writer
- Related Issue #402
- Closes #402
=> Separated Event Writer

src/Sekiban.Core/Documents/InMemoryDocumentRepository.cs, src/Sekiban.Core/Documents/Pools/EventRetrievalInfo.cs, src/Sekiban.Core/Documents/Pools/ISortableIdCondition.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Dynamo/Documents/QueryFilterExtensions.cs, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentRepository.cs, tests/FeatureCheck.Test/AggregateTests/LoyaltyPointTest.cs, tests/Sekiban.Test.Abstructs/Abstructs/EventOrderSpec.cs, tests/Sekiban.Test.Postgres/docker-compose.yml
add between methods
- Related Issue #408
- Closes #408
=> add between methods

.github/workflows/run_test.yml, internalUsages/FeatureCheck.Domain/FeatureCheck.Domain.csproj, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj, tests/FeatureCheck.Test/FeatureCheck.Test.csproj, tests/Mixed.Test/Mixed.Test.csproj, tests/MultiTenant.AggregateTest/MultiTenant.AggregateTest.csproj, tests/Sekiban.Test.Abstructs/Sekiban.Test.Abstructs.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tests/Sekiban.Test.Dynamo/Sekiban.Test.Dynamo.csproj, tests/Sekiban.Test.Postgres/Sekiban.Test.Postgres.csproj
Just build in .net 9 version
- Related Issue #410
- Closes #410
=> Just build in .net 9 version

internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, internalUsages/FeatureCheck.WebApi/FeatureCheck.WebApi.csproj, internalUsages/MemStat.Console/MemStat.Console.csproj, internalUsages/MemStat.Net.Web/MemStat.Net.Web.csproj, internalUsages/Mixed.Domain/Mixed.Domain.csproj, internalUsages/MultiContext.WebApi/MultiContext.WebApi.csproj, internalUsages/MultiTenant.Domain/MultiTenant.Domain.csproj, internalUsages/MultiTenant.WebApi/MultiTenant.WebApi.csproj, internalUsages/SampleProject.Common/SampleProject.Common.csproj, internalUsages/Shipping.Domain/Shipping.Domain.csproj, internalUsages/Shipping.Port/Shipping.Port.csproj, internalUsages/Warehouse.Domain/Warehouse.Domain.csproj, internalUsages/Warehouse.Port/Warehouse.Port.csproj, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Controllers/SekibanApiListController.cs, src/Sekiban.Web/Sekiban.Web.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tools/ConvertAndCopyCosmosItems/ConvertAndCopyCosmosItems.csproj
Nuget Updated
- Related Issue #414
- Closes #414
=> Nuget Updated

internalUsages/FeatureCheck.WebApi.AspireTest/FeatureCheck.WebApi.AspireTest.csproj, internalUsages/FeatureCheck.WebApi.Dynamo/FeatureCheck.WebApi.Dynamo.csproj, internalUsages/FeatureCheck.WebApi.Postgres/FeatureCheck.WebApi.Postgres.csproj, internalUsages/FeatureCheck.WebApi/FeatureCheck.WebApi.csproj, internalUsages/MemStat.Console/MemStat.Console.csproj, internalUsages/MemStat.Net.Web/MemStat.Net.Web.csproj, internalUsages/Mixed.Domain/Mixed.Domain.csproj, internalUsages/MultiContext.WebApi/MultiContext.WebApi.csproj, internalUsages/MultiTenant.Domain/MultiTenant.Domain.csproj, internalUsages/MultiTenant.WebApi/MultiTenant.WebApi.csproj, internalUsages/SampleProject.Common/SampleProject.Common.csproj, internalUsages/Shipping.Domain/Shipping.Domain.csproj, internalUsages/Shipping.Port/Shipping.Port.csproj, internalUsages/Warehouse.Domain/Warehouse.Domain.csproj, internalUsages/Warehouse.Port/Warehouse.Port.csproj, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres.MigrationHost/Sekiban.Infrastructure.Postgres.MigrationHost.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Controllers/SekibanApiListController.cs, src/Sekiban.Web/Sekiban.Web.csproj, tests/Sekiban.Test.CosmosDb/Sekiban.Test.CosmosDb.csproj, tools/ConvertAndCopyCosmosItems/ConvertAndCopyCosmosItems.csproj
to release 0.22.0-preview6
- Related Issue #416
- Closes #416
=> 416 release preview for net 9

.github/workflows/packages.yml
- Related Issue #416
- Closes #416
=> Update packages.yml to build .NET 9 to make package

.github/workflows/packageMemStat.yml, .github/workflows/packages.yml
- Related Issue #420
- Closes #420
=> package yml updated to sepearte memstat release

.github/workflows/packageMemStat.yml, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj
=> update package setting

internalUsages/FeatureCheck.WebApi/Program.cs, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Common/SekibanControllerFeatureProvider.cs, src/Sekiban.Web/Dependency/WebServiceExtension.cs, src/Sekiban.Web/Sekiban.Web.csproj
425 in net 9 sekibanweb swagger UI crash with 500 error
Workaround, skip AggregateListQuery when Interface. Needs to implement your own without using generic.
- Related Issue #425
- Closes #425
=> 425 in net 9 sekibanweb swagger UI crash with 500 error

Samples/Tutorials/1.GetStarted/BookBorrowing.Domain.Test/BookBorrowing.Domain.Test.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Domain/BookBorrowing.Domain.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Cosmos/BookBorrowing.Web.Cosmos.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/BookBorrowing.Web.Dynamo.csproj, Samples/Tutorials/1.GetStarted/BookBorrowing.Web.Dynamo/Program.cs
sample 1 to .NET 9
- Related Issue #418
- Closes #418
=> sample 1 to .NET 9

src/Sekiban.Web/Common/SekibanControllerFeatureProvider.cs
Remove unnecessary controllers.
- Related Issue #431
- Closes #431
=> Remove unnecessary controllers.

.github/workflows/packageMemStat.yml, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
437 add SBOM
- Related Issue #437
- Closes #437
=> 437 add SBOM

.github/workflows/packageMemStat.yml, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
update to release 0.22.1
- Related Issue #440
- Closes #440
=> update to release 0.22.1

Samples/Tutorials/Aspire9SekibanExample/Aspire9SekibanExample.ApiService/Aspire9SekibanExample.ApiService.csproj, Samples/Tutorials/Aspire9SekibanExample/Aspire9SekibanExample.ApiService/Program.cs, Samples/Tutorials/Aspire9SekibanExample/Aspire9SekibanExample.ApiService/Properties/launchSettings.json, Samples/Tutorials/Aspire9SekibanExample/Aspire9SekibanExample.AppHost/Aspire9SekibanExample.AppHost.csproj, Samples/Tutorials/Aspire9SekibanExample/Aspire9SekibanExample.AppHost/Program.cs, Samples/Tutorials/Aspire9SekibanExample/SampleDomain/SampleDomain.csproj
improve .NET 9 sample with aspire
- Related Issue #439
- Closes #439
=> improve .NET 9 sample with aspire

Sekiban.sln, tests/AotTechnicalTesting/AotTechnicalTesting.csproj, tests/AotTechnicalTesting/Definitions/def.cs, tests/AotTechnicalTesting/UnitTest1.cs
- Related Issue #449
- Closes #449
=> adding some test with aot possibility

internalUsages/Pure.Domain/Class1.cs, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure/Class1.cs, src/Sekiban.Pure/Events/EventOrNone.cs
Command Executor Testing samples
Command Executor Testing samples
- Related Issue #452
- Closes #452
=> Command Executor Testing samples

internalUsages/Pure.Domain/Class1.cs, src/MemStat.Net/MemStat.Net.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Pure/Class1.cs, src/Sekiban.Pure/Documents/SortableUniqueIdValue.cs, src/Sekiban.Pure/Exception/ISekibanException.cs, src/Sekiban.Pure/Exception/SekibanAggregateTypeException.cs, src/Sekiban.Pure/Sekiban.Pure.csproj, tests/Pure.Domain.Test/UnitTest1.cs
Completed Super Simple Event Sourcing
- Related Issue #452
- Closes #452
=> Completed Super Simple Event Sourcing

internalUsages/Pure.Domain/Class1.cs, src/Sekiban.Pure.SourceGenerator/Class1.cs, src/Sekiban.Pure/Class1.cs, src/Sekiban.Pure/Exception/SekibanAggregateTypeException.cs, tests/Pure.Domain.Test/UnitTest1.cs
Finished Function Execution
- Related Issue #457
- Closes #457
=> Finished Function Execution

internalUsages/Pure.Domain/Class1.cs, src/Sekiban.Pure.SourceGenerator/Class1.cs, tests/Pure.Domain.Test/UnitTest1.cs
ICommand and ICommandWithAggregateRestriction works with ExecuteFunction
=> ICommand and ICommandWithAggregateRestriction works with ExecuteFunction

.github/workflows/packageMemStat.yml, .github/workflows/packages.yml, .github/workflows/run_test.yml, Sekiban.sln, internalUsages/Pure.Domain/Class1.cs, internalUsages/Pure.Domain/Pure.Domain.csproj, src/Sekiban.Pure.SourceGenerator/CommandExecutionExtensionGenerator.cs, src/Sekiban.Pure.SourceGenerator/EventTypesGenerator.cs, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure/Class1.cs, src/Sekiban.Pure/Sekiban.Pure.csproj, tests/Pure.Domain.Benchmark.Test/Program.cs, tests/Pure.Domain.Benchmark.Test/Pure.Domain.Benchmark.Test.csproj, tests/Pure.Domain.Test/Pure.Domain.Test.csproj, tests/Pure.Domain.Test/UnitTest1.cs
- Related Issue #469
- Closes #469
=> 469 test native aot compatibility

internalUsages/Pure.Domain/Class1.cs, src/Sekiban.Pure.SourceGenerator/CommandExecutionExtensionGenerator.cs, src/Sekiban.Pure/Class1.cs, tests/Pure.Domain.Test/Pure.Domain.Test.csproj, tests/Pure.Domain.Test/UnitTest1.cs
[Pure] working on the Command Resource 
- Related Issue #472
- Closes #472
=> [Pure] working on the Command Resource 

src/Sekiban.Pure/Class1.cs, tests/Pure.Domain.Test/UnitTest1.cs
Add Publish Only
- Related Issue #474
- Closes #474
=> Add Publish Only

internalUsages/Pure.Domain/ShoppingCartItemAdded.cs, internalUsages/Pure.Domain/ShoppingCartProjector.cs, internalUsages/Pure.Domain/UserProjector.cs, src/Sekiban.Pure/Projectors/IAggregateProjector.cs, src/Sekiban.Pure/Repositories/Repository.cs
Working on Simple Multi Projector
- Related Issue #466
- Closes #466
=> Working on Simple Multi Projector

internalUsages/Pure.Domain/UserProjector.cs, src/Sekiban.Pure/Projectors/IAggregateProjector.cs, src/Sekiban.Pure/Repositories/Repository.cs, tests/Pure.Domain.Test/UnitTest1.cs
add multi repository test and adjust it
- Related Issue #479
- Closes #479
=> add test and adjust it

internalUsages/Pure.Domain/UserProjector.cs, src/Sekiban.Pure.SourceGenerator/CommandExecutionExtensionGenerator.cs, src/Sekiban.Pure.SourceGenerator/EventTypesGenerator.cs, src/Sekiban.Pure/Events/Event.cs, src/Sekiban.Pure/Events/IEvent.cs, src/Sekiban.Pure/Exception/ISekibanException.cs, src/Sekiban.Pure/Projectors/IAggregateProjector.cs, src/Sekiban.Pure/Projectors/IMultiProjectionEventSelector.cs, src/Sekiban.Pure/Projectors/IMultiProjector.cs, src/Sekiban.Pure/Projectors/MultiProjectionEventSelector.cs, src/Sekiban.Pure/Projectors/MultiProjectionState.cs, src/Sekiban.Pure/Query/IQueryCommon.cs, src/Sekiban.Pure/Repositories/Repository.cs, src/Sekiban.Pure/Sekiban.Pure.csproj, src/Sekiban.Pure/Types/GeneralTypeExtensions.cs, tests/Pure.Domain.Test/UnitTest1.cs
simple multi projection
- Related Issue #481
- Closes #481
=> simple multi projection

Sekiban.sln, src/Sekiban.Pure.OrleansEventSourcing/Class1.cs, src/Sekiban.Pure.OrleansEventSourcing/OrleansAggregate.cs, src/Sekiban.Pure.OrleansEventSourcing/Sekiban.Pure.OrleansEventSourcing.csproj, src/Sekiban.Pure/Aggregates/Aggregate.cs, src/Sekiban.Pure/Aggregates/IAggregate.cs, src/Sekiban.Pure/Command/Executor/CommandExecutor.cs, src/Sekiban.Pure/Command/Executor/CommandResponse.cs, src/Sekiban.Pure/Command/Handlers/ICommandHandler.cs, src/Sekiban.Pure/Command/Handlers/ICommandWithHandler.cs, src/Sekiban.Pure/Command/Handlers/ICommandWithHandlerAsync.cs, src/Sekiban.Pure/Documents/PartitionKeys.cs, src/Sekiban.Pure/Exception/SekibanAggregateTypeException.cs, src/Sekiban.Pure/Exception/SekibanCommandHandlerNotMatchException.cs, src/Sekiban.Pure/Sekiban.Pure.csproj
494 for orleans sync settings
- Related Issue #494
- Closes #494
=> 494 for orleans sync settings

.github/workflows/packages.yml
=> Include IndexedDb

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core.DotNet/Sekiban.Core.DotNet.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.IndexedDb/Sekiban.Infrastructure.IndexedDb.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
=> fixed version too

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> Bump version to 1.0.0-preview2 for all projects and update package references accordingly

Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> fixed release setting for source generator

Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Program.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecast.cs, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Parts/SekibanSerializationTypesChecker.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/MultiProjectorTypesGenerator.cs, src/Sekiban.Pure.SourceGenerator/QueryExecutionExtensionGenerator.cs, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Query/IQueryTypes.cs, src/Sekiban.Pure/Sekiban.Pure.csproj
=> Bump version to 1.0.0-preview6 for all projects and update package references accordingly

Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Program.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/Components/App.razor, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/Components/Pages/Weather.razor, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/OrleansSekiban.Web.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/WeatherApiClient.cs
=> Update orleans sample

Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Program.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/DeletedWeatherForecast.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekibanDomainEventsJsonContext.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/RemoveWeatherForecastCommand.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/UpdateWeatherForecastLocationCommand.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecast.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastDeleted.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastLocationUpdated.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastProjector.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastQuery.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/Components/Pages/Weather.razor, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/WeatherApiClient.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.code-workspace
simple weather sample but has change command etc.
- Closes #
=> sekiban pure sample

Samples/Tutorials/OrleansSekiban/.template.config/template.json, Samples/Tutorials/OrleansSekiban/HowToRelease.md, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Program.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Properties/launchSettings.json, Samples/Tutorials/OrleansSekiban/OrleansSekiban.AppHost/OrleansSekiban.AppHost.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/DeletedWeatherForecast.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekibanDomainEventsJsonContext.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/RemoveWeatherForecastCommand.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/UpdateWeatherForecastLocationCommand.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastDeleted.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastLocationUpdated.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastProjector.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/WeatherForecastQuery.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ServiceDefaults/OrleansSekiban.ServiceDefaults.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/Components/Pages/Weather.razor, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/OrleansSekiban.Web.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Web/WeatherApiClient.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.code-workspace, Samples/Tutorials/OrleansSekiban/OrleansSekibanTemplate.csproj, Samples/Tutorials/OrleansSekiban/README.md
=> 521 pure orleans template

.github/workflows/packageTemplate.yml
=> Rename workflow step and correct path for NuGet package push

README.md
=> Update README to include information about the new Sekiban version with Orleans support and provide links to relevant documentation

README_Pure.md, README_Pure_For_LLM.md, README_Pure_JP.md
=> Update README files to enhance project setup instructions and API configuration for Sekiban projects

README_Pure.md, README_Pure_For_LLM.md, README_Pure_JP.md
=> Enhance documentation to include usage of third generic parameter for state-based constraints in ICommandWithHandler interface

README_Pure.md, README_Pure_For_LLM.md, README_Pure_JP.md
=> 537 fix llm doc

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/appsettings.Development.json, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.AppHost/Program.cs
=> Bump package version to 1.0.7 and update logging configuration in templates

README_Pure_For_LLM.md
=> Enhance README_Pure_For_LLM.md with detailed explanations for List and Non-List Queries, including required implementations and example code.

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/QueryExecutionExtensionGenerator.cs, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
Update for source generator types
- Closes #
=> Update for source generator types

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/QueryExecutionExtensionGenerator.cs, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> Bump version to 1.0.0-preview8 for all projects and update package references accordingly

.github/workflows/run_test.yml
=> Increase timeout for flaky tests in GitHub Actions workflow

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/.clinerules, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.AppHost/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/Aggregates/WeatherForecasts/Commands/DeleteWeatherForecastCommand.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/WeatherForecastQuery.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/Base/BaseTest.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/OrleansSekiban.Playwright.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/PageObjects/WeatherPage.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/README.md, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/Tests/PlaywrightInstallationTest.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/Tests/WeatherForecastTests.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/install-browsers.sh, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/run-tests.sh, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/WeatherForecastOrleansTests.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/WeatherForecastTests.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Web/Components/Pages/Weather.razor, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.sln, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/Sekiban.Instruction.md
=> Add Playwright testing framework and scripts for end-to-end tests

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> Bump version to 1.0.0-preview9 for all Sekiban.Pure packages and update dependencies

.github/workflows/packageTemplate.yml, Samples/Tutorials/AspireEventSample/AspireEventSample.ApiService/AspireEventSample.ApiService.csproj, Samples/Tutorials/AspireEventSample/AspireEventSample.AppHost/AspireEventSample.AppHost.csproj, Samples/Tutorials/AspireEventSample/AspireEventSample.AppHost/Program.cs, Samples/Tutorials/AspireEventSample/AspireEventSample.NUnitTest/AspireEventSample.NUnitTest.csproj, Samples/Tutorials/AspireEventSample/AspireEventSample.ServiceDefaults/AspireEventSample.ServiceDefaults.csproj, Samples/Tutorials/AspireEventSample/AspireEventSample.UnitTest/AspireEventSample.UnitTest.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.AppHost/OrleansSekiban.AppHost.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.AppHost/Program.cs, Samples/Tutorials/OrleansSekiban/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ServiceDefaults/OrleansSekiban.ServiceDefaults.csproj, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.AppHost/OrleansSekiban.AppHost.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.AppHost/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/OrleansSekiban.Playwright.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ServiceDefaults/OrleansSekiban.ServiceDefaults.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
Template update to latest
- Related Issue #565
- Closes #565
=> Bump package version to 1.0.10 and update dependencies for Sekiban.Pure.Templates

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> release update

src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> update version to be able to make it not to downgradae

.github/workflows/packageTemplate.yml, internalUsages/OrleansSekiban.ApiService/appsettings.json, internalUsages/OrleansSekiban.AppHost/appsettings.json, internalUsages/OrleansSekiban.Web/appsettings.json, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Parts/SystemTextJsonStorageSerializer.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/appsettings.json, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekibanDomainEventsJsonContext.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> 590 add systemtextjsonstorageserializer

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/infrastructure/azure_appservice/how.md
=> feat: update package version to 1.0.13 and remove specific Azure tenant login instruction from documentation

internalUsages/OrleansSekiban.Domain/Aggregates/WeatherForecasts/Payloads/DeletedWeatherForecast.cs, internalUsages/OrleansSekiban.Domain/Aggregates/WeatherForecasts/Payloads/WeatherForecast.cs, internalUsages/OrleansSekiban.Domain/Aggregates/WeatherForecasts/WeatherForecastProjector.cs, internalUsages/OrleansSekiban.Domain/OrleansSekibanDomainEventsJsonContext.cs, internalUsages/OrleansSekiban.Domain/WeatherForecastQuery.cs, internalUsages/OrleansSekiban.Unit/WeatherForecastOrleansTests.cs, internalUsages/OrleansSekiban.Unit/WeatherForecastTests.cs, src/Sekiban.Pure.Orleans/Parts/SekibanSerializationTypesChecker.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/Aggregates/WeatherForecasts/Payloads/DeletedWeatherForecast.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekibanDomainEventsJsonContext.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> feat: add DeletedWeatherForecast payload and update serialization context

internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.AppHost/Program.cs, internalUsages/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Grains/AggregateEventHandlerGrain.cs, src/Sekiban.Pure.Orleans/Grains/AggregateEventHandlerGrainToPersist.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
- Related Issue #600
- Closes #600
=> improved serialization for cosmos

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core.DotNet/Query/MultiProjections/Projections/MultiProjectionSnapshotGenerator.cs, src/Sekiban.Core.DotNet/Sekiban.Core.DotNet.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.IndexedDb/Sekiban.Infrastructure.IndexedDb.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
=> Repository deliver events little by little

tools/ProjectionFromJsonL/JsonlBatchProcessor.cs, tools/ProjectionFromJsonL/Program.cs, tools/ProjectionFromJsonL/ProjectionFromJsonL.csproj
=> Add JsonlBatchProcessor and Program files for batch processing of JSONL data

internalUsages/OrleansSekiban.Domain/PartitionKeysJsonConverter.cs, src/Sekiban.Pure.CosmosDb/SourceGenCosmosSerializer.cs, src/Sekiban.Pure.SourceGenerator/DomainTypesGenerator.cs, src/Sekiban.Pure/Events/InMemoryEventReader.cs, src/Sekiban.Pure/Query/QueryResult.cs, src/Sekiban.Pure/SekibanDomainTypes.cs, src/Sekiban.Pure/Serialize/SekibanReflectionSerializer.cs, src/Sekiban.Pure/Serialize/SekibanSerializer.cs
=> refactor: improve deserialization error handling and update interface definitions

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> feat: update package version to 1.0.16 in project files and workflow

.github/workflows/packageTemplate.yml, Samples/Tutorials/OrleansSekiban/OrleansSekiban.ApiService/Program.cs, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/appsettings.json
=> feat: update package version to 1.0.18 in project files and workflow

clinerules_bank/tasks/issue619_01_keep_all.234211.md, clinerules_bank/tasks/issue619_01_keep_all.md, internalUsages/OrleansSekiban.AppHost/Program.cs, internalUsages/OrleansSekiban.Web/Components/Pages/Weather.razor, src/Sekiban.Pure.Orleans/Grains/MultiProjectorGrain.cs
=> refactor: improve stream event handling in MultiProjectorGrain by changing buffer implementation and processing logic

clinerules_bank/tasks/issue621_02.193935.md, clinerules_bank/tasks/issue621_02.md, clinerules_bank/tasks/issue621_wait_for.010721.md, clinerules_bank/tasks/issue621_wait_for.165448.md, clinerules_bank/tasks/issue621_wait_for.md, internalUsages/OrleansSekiban.ApiService/Program.cs, internalUsages/OrleansSekiban.Domain/WeatherForecastQuery.cs, internalUsages/OrleansSekiban.Web/Components/Pages/Weather.razor, internalUsages/OrleansSekiban.Web/WeatherApiClient.cs, src/Sekiban.Pure.Orleans/Grains/MultiProjectorGrain.cs, src/Sekiban.Pure.Orleans/IMultiProjectorGrain.cs, src/Sekiban.Pure.Orleans/Parts/SekibanOrleansExecutor.cs, src/Sekiban.Pure.Orleans/SekibanOrleansExecutor.cs, src/Sekiban.Pure/Command/Executor/CommandResponse.cs, src/Sekiban.Pure/Documents/SortableUniqueIdWaitHelper.cs, src/Sekiban.Pure/Query/IWaitForSortableUniqueId.cs
Wait for the multi projection to have specific events
- Closes #
=> fix: update DefaultPollingIntervalMs to improve polling behavior

templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/appsettings.json
=> feat: add Application Insights telemetry support and configuration

internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Parts/NewtonsoftJsonSekibanOrleansSerializer.cs, src/Sekiban.Pure.Orleans/Parts/OrleansEventExtensions.cs, src/Sekiban.Pure.Orleans/Parts/SekibanSerializationTypesChecker.cs, src/Sekiban.Pure.Orleans/Parts/SerializableMultiProjectionState.cs, src/Sekiban.Pure.Orleans/Parts/SystemTextJsonStorageSerializer.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Command/Executor/CommandExecutor.cs, src/Sekiban.Pure/Command/Executor/CommandResponse.cs, src/Sekiban.Pure/Sekiban.Pure.csproj
=> Add ToSimpleCommandResponse Methods

internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Grains/MultiProjectorGrain.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Documents/SortableUniqueIdValue.cs, src/Sekiban.Pure/Projectors/AggregateListProjector.cs, src/Sekiban.Pure/Projectors/IAggregateListProjectorAccessor.cs, src/Sekiban.Pure/Projectors/IMultiProjectorsType.cs, src/Sekiban.Pure/Projectors/MultiProjectionState.cs, src/Sekiban.Pure/Projectors/SerializableAggregateListProjector.cs, src/Sekiban.Pure/Sekiban.Pure.csproj
=> chore: update package versions to 1.0.1-preview12 across multiple projects

.github/workflows/packageTemplate.yml, internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> chore: update Sekiban.Pure package versions to 1.0.1-preview13 and update template version to 1.0.22

README.md
=> Update Sekiban MCP integration command for Claude Desktop to improve documentation access

src/Sekiban.Core.DotNet/Documents/InMemoryDocumentRepository.cs, src/Sekiban.Core.DotNet/Documents/Pools/BetweenSortableIdCondition.cs, src/Sekiban.Core.DotNet/Documents/Pools/ISortableIdCondition.cs, src/Sekiban.Core.DotNet/Documents/Pools/SinceSortableIdCondition.cs, src/Sekiban.Core.DotNet/Documents/Pools/SortableIdConditionNone.cs, src/Sekiban.Infrastructure.Cosmos/Documents/CosmosDocumentRepository.cs, src/Sekiban.Infrastructure.Dynamo/Documents/DynamoDocumentRepository.cs, src/Sekiban.Infrastructure.Dynamo/Documents/QueryFilterExtensions.cs, src/Sekiban.Infrastructure.IndexedDb/Runtime/src/index.ts, src/Sekiban.Infrastructure.Postgres/Documents/PostgresDocumentRepository.cs, tests/Sekiban.Test.Abstructs/Abstructs/CommandOrderSpec.cs, tests/Sekiban.Test.Abstructs/Abstructs/EventOrderSpec.cs, tests/Sekiban.Test.CosmosDb/Stories/CosmosCommandOrderSpec.cs, tests/Sekiban.Test.Dynamo/Tests/CommandOrderSpecDynamo.cs, tests/Sekiban.Test.IndexedDb/Tests/IndexedDbCommandOrderSpec.cs, tests/Sekiban.Test.Postgres/Tests/CommandOrderSpecPostgres.cs
This PR aligns the behavior of SortableIdCondition when retrieving events and commands.
The CosmosDB implementation **does not** include start and end bounds and seems to work as expected, while the DynamoDB, PostgreSQL, and IndexedDB implementations **does** include bounds.
I have also added some tests for bounds and ordering.
- Closes #
=> Fix boundary errors

src/Sekiban.Aspire.Infrastructure.Cosmos/Sekiban.Aspire.Infrastructure.Cosmos.csproj, src/Sekiban.Core.DotNet/Sekiban.Core.DotNet.csproj, src/Sekiban.Core/Sekiban.Core.csproj, src/Sekiban.Infrastructure.Aws.S3/Sekiban.Infrastructure.Aws.S3.csproj, src/Sekiban.Infrastructure.Azure.Storage.Blobs/Sekiban.Infrastructure.Azure.Storage.Blobs.csproj, src/Sekiban.Infrastructure.Cosmos/Sekiban.Infrastructure.Cosmos.csproj, src/Sekiban.Infrastructure.Dynamo/Sekiban.Infrastructure.Dynamo.csproj, src/Sekiban.Infrastructure.IndexedDb/Sekiban.Infrastructure.IndexedDb.csproj, src/Sekiban.Infrastructure.Postgres/Sekiban.Infrastructure.Postgres.csproj, src/Sekiban.Testing/Sekiban.Testing.csproj, src/Sekiban.Web/Sekiban.Web.csproj
=> 664 core new version 202507

.github/workflows/packagesPure.yml, internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, internalUsages/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.Dapr/Sekiban.Pure.Dapr.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
release dapr test version
- Closes #
=> feat: Update package versions to 1.0.1-preview15 across all projects and add Dapr packaging to workflow

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj
=> chore: update package version to 1.1.2 in project files and workflow

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.ApiService/DaprSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.AppHost/DaprSekiban.AppHost.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.AppHost/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.Domain/DaprSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/DaprSekiban.EventRelay.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/Dockerfile, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/Program.cs, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/Properties/launchSettings.json, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/appsettings.Development.json, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/appsettings.json, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.Unit/DaprSekiban.Unit.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.sln, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/dapr-components/pubsub.yaml, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/6.dapr-components/1.cosmos-statestore-component.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/6.dapr-components/2.servicebus-pubsub-component.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/8.blazor/env-module.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/9.eventrelay/1.container-app.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/9.eventrelay/2.diagnostic-settings.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/9.eventrelay/env-module.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/aca_apps.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/aca_main.bicep, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/code_deploy_eventrelay.sh, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/infrastructure/azure_container_apps/how.md, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> infrastracture for dapr ACA

.github/workflows/packageTemplate.yml, templates/Sekiban.Pure.Templates/Sekiban.Pure.Templates.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.ApiService/DaprSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.Domain/DaprSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.EventRelay/DaprSekiban.EventRelay.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Dapr.Aspire/DaprSekiban.Unit/DaprSekiban.Unit.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Domain/OrleansSekiban.Domain.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Playwright/OrleansSekiban.Playwright.csproj, templates/Sekiban.Pure.Templates/content/Sekiban.Orleans.Aspire/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj
=> update for orleans and dapr template C#

Sekiban.sln, internalUsages/Dcb.Domain/ClassRoom/ClassRoomTag.cs, internalUsages/Dcb.Domain/Student/StudentTag.cs, src/Sekiban.Dcb.Orleans/Grains/ITagConsistentGrain.cs, src/Sekiban.Dcb.Orleans/Grains/ITagStateGrain.cs, src/Sekiban.Dcb.Orleans/Grains/TagConsistentGrain.cs, src/Sekiban.Dcb.Orleans/Grains/TagStateGrain.cs, src/Sekiban.Dcb.Orleans/OrleansActorObjectAccessor.cs, src/Sekiban.Dcb.Orleans/OrleansCommandExecutor.cs, src/Sekiban.Dcb.Orleans/Sekiban.Dcb.Orleans.csproj, src/Sekiban.Dcb.Orleans/ServiceCollectionExtensions.cs, src/Sekiban.Dcb/Actors/GeneralSekibanExecutor.cs, src/Sekiban.Dcb/Actors/GeneralTagConsistentActor.cs, src/Sekiban.Dcb/Actors/GeneralTagStateActor.cs, src/Sekiban.Dcb/Domains/SimpleEventTypes.cs, src/Sekiban.Dcb/Domains/SimpleTagProjectorTypes.cs, src/Sekiban.Dcb/Domains/SimpleTagStatePayloadTypes.cs, src/Sekiban.Dcb/ISekibanExecutor.cs, src/Sekiban.Dcb/Tags/ConsistencyTag.cs, src/Sekiban.Dcb/Tags/ITag.cs, src/Sekiban.Dcb/Tags/NonConsistencyTag.cs, src/Sekiban.Dcb/Tags/TagExtensions.cs, tests/Sekiban.Dcb.Postgres.Tests/DebugDatabaseContentTest.cs, tests/Sekiban.Dcb.Postgres.Tests/PostgresWithActorsTests.cs, tests/Sekiban.Dcb.Tests/DuplicateRegistrationTests.cs, tests/Sekiban.Dcb.Tests/InMemoryCommandContextTest.cs, tests/Sekiban.Dcb.Tests/InMemoryCommandExecutorTest.cs, tests/Sekiban.Dcb.Tests/OptimisticLockingTest.cs
=> refactor: Simplify command execution by using inline handler function in domain tests

internalUsages/DcbOrleans.ApiService/Program.cs
=> feat: Enable CORS in development environment for easier testing

internalUsages/OrleansSekiban.ApiService/OrleansSekiban.ApiService.csproj, internalUsages/OrleansSekiban.Unit/OrleansSekiban.Unit.csproj, src/Sekiban.Pure.AspNetCore/Sekiban.Pure.AspNetCore.csproj, src/Sekiban.Pure.CosmosDb/Sekiban.Pure.CosmosDb.csproj, src/Sekiban.Pure.Dapr/Sekiban.Pure.Dapr.csproj, src/Sekiban.Pure.NUnit/Sekiban.Pure.NUnit.csproj, src/Sekiban.Pure.Orleans.NUnit/Sekiban.Pure.Orleans.NUnit.csproj, src/Sekiban.Pure.Orleans.xUnit/Sekiban.Pure.Orleans.xUnit.csproj, src/Sekiban.Pure.Orleans/Grains/AggregateEventHandlerGrain.cs, src/Sekiban.Pure.Orleans/Sekiban.Pure.Orleans.csproj, src/Sekiban.Pure.Postgres/Sekiban.Pure.Postgres.csproj, src/Sekiban.Pure.ReadModel/Sekiban.Pure.ReadModel.csproj, src/Sekiban.Pure.SourceGenerator/Sekiban.Pure.SourceGenerator.csproj, src/Sekiban.Pure.xUnit/Sekiban.Pure.xUnit.csproj, src/Sekiban.Pure/Sekiban.Pure.csproj
=> chore: Update package versions to 1.0.1-preview24 across all projects

internalUsages/Dcb.Domain/DomainType.cs, internalUsages/Dcb.Domain/Projections/WeatherForecastProjection.cs, internalUsages/Dcb.Domain/Projections/WeatherForecastProjectorWithTagStateProjector.cs, src/Sekiban.Dcb/Actors/GeneralEventProvider.cs, src/Sekiban.Dcb/Actors/GeneralMultiProjectionActor.cs, src/Sekiban.Dcb/Actors/IEventSubscription.cs, src/Sekiban.Dcb/Actors/IGeneralEventProvider.cs, src/Sekiban.Dcb/Actors/IMultiProjectionEventFeeder.cs, src/Sekiban.Dcb/InMemory/InMemoryEventSubscription.cs, src/Sekiban.Dcb/InMemory/InMemoryMultiProjectionEventFeeder.cs, src/Sekiban.Dcb/MultiProjections/GenericTagMultiProjector.cs, src/Sekiban.Dcb/MultiProjections/ISafeAndUnsafeStateAccessor.cs, src/Sekiban.Dcb/MultiProjections/SafeUnsafeMultiProjectionState.cs, src/Sekiban.Dcb/MultiProjections/SafeUnsafeProjectionState.cs, src/Sekiban.Dcb/MultiProjections/SafeUnsafeProjectionStateV7.cs, tests/Sekiban.Dcb.Tests/GeneralEventProviderIntegrationTests.cs, tests/Sekiban.Dcb.Tests/GeneralEventProviderTests.cs, tests/Sekiban.Dcb.Tests/GenericTagMultiProjectorWithTagGroupTests.cs, tests/Sekiban.Dcb.Tests/InMemoryEventSubscriptionTests.cs, tests/Sekiban.Dcb.Tests/SafeUnsafeProjectionStateTests.cs, tests/Sekiban.Dcb.Tests/SafeUnsafeProjectionStateV7Tests.cs, tests/Sekiban.Dcb.Tests/SafeUnsafeStateAccessorTests.cs
Improve management of processed event IDs and introduce new interfaces for event handling. Add comprehensive tests to ensure correct behavior during state transitions and event processing. Refactor existing code to utilize updated interfaces and enhance filtering capabilities for event subscriptions.
=> Enhance event processing and state management interfaces

templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.ApiService/Program.cs, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.ApiService/SekibanDcbOrleans.ApiService.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Domain/SekibanDcbOrleans.Domain.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Domain/Weather/CreateWeatherForecast.cs, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Domain/Weather/TemperatureCelsius.cs, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Web/Components/Pages/Weather.razor, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Web/WeatherApiClient.cs
Upgrade Sekiban.Dcb package versions and improve weather forecast processing to support server-side generation of ForecastId and enhance payload structure for external compatibility.
=> Update Sekiban.Dcb packages and enhance weather forecast handling

templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.ApiService/Program.cs, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.ApiService/SekibanDcbOrleans.ApiService.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Domain/SekibanDcbOrleans.Domain.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/3.cosmos/1.create.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/3.cosmos/2.database.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/3.cosmos/3.container.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/3.cosmos/4.orleans-cluster-container.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/3.cosmos/6.save-keyvault.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/7.backend/6.app-settings.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/code_deploy_backend.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/code_deploy_frontend.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/create_resource_group.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/generate_azure_credentials.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/how.md, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/purge_keyvault.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/runbicep.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_appservice/user_access_keyvault.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/3.cosmos/2.database.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/3.cosmos/3.container.bicep, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/code_deploy_backend.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/code_deploy_frontend.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/create_container_registry.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/create_log-analytics.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/create_resource_group.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/generate_azure_credentials.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/how.md, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/purge_keyvault.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/runbicep.sh, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/infrastructure/azure_container_apps/user_access_keyvault.sh
Refactor Bicep templates to use 'SekibanDcb' as the database name and improve deployment scripts for better argument handling, allowing support for both environment names and full paths to configuration files.
=> Update Cosmos DB configurations and enhance script handling

.github/workflows/packagesDcbTemplate.yml, templates/Sekiban.Dcb.Templates/Sekiban.Dcb.Templates.csproj
Change the package version in the push command and project file to reflect the new version 0.1.2.
=> Update Sekiban.Dcb.Templates package version to 0.1.2

.github/workflows/packagesDcbTemplate.yml, templates/Sekiban.Dcb.Templates/Sekiban.Dcb.Templates.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.ApiService/SekibanDcbOrleans.ApiService.csproj, templates/Sekiban.Dcb.Templates/content/Sekiban.Dcb.Orleans/SekibanDcbOrleans.Domain/SekibanDcbOrleans.Domain.csproj
Update the Sekiban.Dcb package to version 1.0.2-preview08 and Sekiban.Dcb.Templates to version 0.1.3 in project files.
=> Update Sekiban.Dcb and Sekiban.Dcb.Templates package versions

.github/workflows/run_test_dcb.yml, .github/workflows/run_test_pure.yml, tests/Sekiban.Dcb.BlobStorage.AzureStorage.Unit/AzuriteTestFixture.cs, tests/Sekiban.Dcb.BlobStorage.AzureStorage.Unit/Sekiban.Dcb.BlobStorage.AzureStorage.Unit.csproj, tests/Sekiban.Dcb.BlobStorage.AzureStorage.Unit/SimpleStorageTests.cs
Enhance test workflows to include additional paths for DCB and Pure projects. Refactor AzuriteTestFixture to utilize Testcontainers for improved container management and update tests to handle larger payloads.
=> Update test workflows and refactor Azurite tests
